server:
  port: 8080
  servlet: 
    context-path: /leader
spring:
  profiles:
    active: dev
  jackson:
    time-zone: "GMT+8"
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    pathmatch:
      # springboot2.0x中，默认不支持带后缀.do
      use-suffix-pattern: true