apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-redis-static-pvc
  namespace: k8s-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Mi
  storageClassName: nfs-static-pool-group