apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01-100m
  namespace: k8s-test
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static-pool-group
  nfs:
    path: /nfs/data/pv-static-pool-01
    server: 172.30.0.139
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02-200m
  namespace: k8s-test
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static-pool-group
  nfs:
    path: /nfs/data/pv-static-pool-02
    server: 172.30.0.139
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03-1gi
  namespace: k8s-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static-pool-group
  nfs:
    path: /nfs/data/pv-static-pool-03
    server: 172.30.0.139









