kind: Deployment
apiVersion: apps/v1
metadata:
  name: leader
  namespace: mdf-prod
  labels:
    app: leader
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"leader"},"name":"leader","namespace":"mdf-prod"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"selector":{"matchLabels":{"app":"leader"}},"strategy":{"rollingUpdate":{"maxSurge":"50%","maxUnavailable":"50%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"leader"}},"spec":{"containers":[{"image":"registry.cn-beijing.aliyuncs.com/power-matrix/leader:snapshot-22","imagePullPolicy":"Always","name":"app","ports":[{"containerPort":8080,"name":"tcp-8080","protocol":"TCP"}],"resources":{"limits":{"cpu":"2000m","memory":"2000Mi"}},"terminationMessagePath":"/opt/application/logs/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"aliyun-docker-hub-secrets"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30}}}}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: leader
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: leader
    spec:
      containers:
        - name: app
          image: 'registry.cn-beijing.aliyuncs.com/power-matrix/leader:snapshot-22'
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2000Mi
          terminationMessagePath: /opt/application/logs/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: aliyun-docker-hub-secrets
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: leader-prod-service-np
  namespace: mdf-prod
  labels:
    app: leader
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"leader"},"name":"leader-prod-service-np","namespace":"mdf-prod"},"spec":{"ports":[{"name":"http-8080","nodePort":32600,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"leader"},"sessionAffinity":"None","type":"NodePort"}}
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32600
  selector:
    app: leader
  #clusterIP: 10.233.17.76
  #clusterIPs:
  #  - 10.233.17.76
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

---
kind: Service
apiVersion: v1
metadata:
  name: leader-prod-service-inner
  namespace: mdf-prod
  labels:
    app: leader
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"leader"},"name":"leader-prod-service-inner","namespace":"mdf-prod"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"leader"},"sessionAffinity":"None","type":"ClusterIP"}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: leader
  #clusterIP: 10.233.59.4
  #clusterIPs:
  # - 10.233.59.4
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster















