---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mdf-prod-mysql-config
  namespace: mdf-prod
  annotations:
    kubesphere.io/alias-name: mdf-prod
    kubesphere.io/creator: dev-liu
    kubesphere.io/description: 'mdf prod 环境mysql-config配置文件信息，即: /etc/mysql/my.cnf信息'
data:
  my.cnf: |
    [client]
    default-character-set=utf8mb4
     
    [mysql]
    default-character-set=utf8mb4
     
    [mysqld]
    init_connect='SET collation_connection = utf8mb4_unicode_ci'
    init_connect='SET NAMES utf8mb4'
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    skip-character-set-client-handshake
    skip-name-resolve
    lower_case_table_names=1


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mdf-prod-mysql-pvc
  namespace: mdf-prod
  annotations:
    kubesphere.io/alias-name: mdf-prod
    kubesphere.io/creator: dev-liu
    kubesphere.io/description: mdf prod 环境 mysql外部存储挂载
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
    volume.kubernetes.io/selected-node: node2
    volume.kubernetes.io/storage-provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pvc-84db8787-f5a1-442e-9919-9e7f33f39d61
  storageClassName: local
  volumeMode: Filesystem


---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mdf-prod-mysql
  namespace: mdf-prod
  labels:
    app: mdf-prod-mysql
  annotations:
    kubesphere.io/alias-name: mdf-prod
    kubesphere.io/creator: dev-liu
    kubesphere.io/description: 线上环境数据库
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mdf-prod-mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mdf-prod-mysql
      annotations:
        kubesphere.io/creator: dev-liu
        kubesphere.io/imagepullsecrets: '{}'
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-0rfzns
          persistentVolumeClaim:
            claimName: mdf-prod-mysql-pvc
        - name: volume-ld5ma0
          configMap:
            name: mdf-prod-mysql-config
            defaultMode: 420
      containers:
        - name: container-gp3ixe
          image: 'poweryangcl/mysql8.0:v2.0.0'
          ports:
            - name: tcp-3306
              containerPort: 3306
              protocol: TCP
            - name: tcp-33060
              containerPort: 33060
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: XianYue1998@
          resources:
            limits:
              cpu: '1'
              memory: 2000Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-0rfzns
              mountPath: /var/lib/mysql
            - name: volume-ld5ma0
              readOnly: true
              mountPath: /etc/mysql/conf.d
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: mdf-prod-mysql-kg6v
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10

---
kind: Service
apiVersion: v1
metadata:
  name: mdf-prod-mysql-service-inner
  namespace: mdf-prod
  labels:
    app: mdf-prod-mysql-service-inner
  annotations:
    kubesphere.io/alias-name: mdf-prod
    kubesphere.io/creator: dev-liu
spec:
  ports:
    - name: http-3306
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mdf-prod-mysql
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster


---
kind: Service
apiVersion: v1
metadata:
  name: mdf-prod-mysql-service-np
  namespace: mdf-prod
  labels:
    app: mdf-prod-mysql-service-np
  annotations:
    kubesphere.io/alias-name: mdf-prod
    kubesphere.io/creator: dev-liu
spec:
  ports:
    - name: http-3306
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31277
  selector:
    app: mdf-prod-mysql
  clusterIP: 10.233.50.95
  clusterIPs:
    - 10.233.50.95
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster









